#This will populate the metrics in all the tiers, under this path(not recommended)
#metricPrefix: "Custom Metrics|Redis"
#The following prefix will populate the metrics under one tier
metricPrefix: "Server|Component:<TIER NAME OR TIER ID>|Custom Metrics|Redis"

#Add your list of Redis servers here.
servers:
  - name: "Server1"
    host: "localhost"
    port: "6379"
    password: ""
    encryptedPassword: ""
    useSSL: false

#The following connection section is not mandatory. It needs to be used only when useSSL is true and
#using custom truststore and keystore.
connection:
    socketTimeout: 5000 # Read Timeout
    connectTimeout: 5000 # Connection Timeout


    sslVerifyHostname: true
    sslProtocols: ["TLS"] # If customizing, add only one value by replacing "TLS". By default TLSv1, TLSv1.1, TLSv1.2 are supported.

    sslTrustStorePath: "" # If not set, will set value from "-Dappdynamics.agent.monitors.truststore.path=/path/cacerts" if present, else will set value as <MachineAgentHome>/conf/extensions-cacerts.jks.
    sslTrustStorePassword: "" # If not set, will set value from "-Dappdynamics.agent.monitors.truststore.password=password".
    sslTrustStoreEncryptedPassword: "" ## If not set, will set value from "-Dappdynamics.agent.monitors.truststore.encryptedPassword=ghrr121fgk23-2636guu".

    #The following are only required when mutual auth is enabled. Else they can be ignored.
    sslKeyStorePath: "" # If not set, will set value from "-Dappdynamics.agent.monitors.keystore.path=/path/clientcerts" if present, else will set value as <MachineAgentHome>/conf/extensions-clientcerts.jks.
    sslKeyStorePassword: "" # If not set, will set value from "-Dappdynamics.agent.monitors.keystore.password=password".
    sslKeyStoreEncryptedPassword: "" # If not set, will set value from "-Dappdynamics.agent.monitors.keystore.encryptedPassword=ghrr121fgk23-2636guu".

#Encryption key for Encrypted password.
encryptionKey: ""

# Each server instance needs 3 threads, one for the server instance itself, one for info call to the Redis server and one for slowlog call to the server.
# So, please change the value accordingly(Based on the number of server instances you are monitoring).
numberOfThreads: 21

enableHealthChecks: false

#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier -->not for derived metrics
#   convert --> not for derived metrics
#   delta --> not for derived metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
metrics:
    Slowlog:
        - no_of_new_slow_logs:
            alias: "no_of_new_slow_logs"
    Info:
        Clients: #Information about the client connections
            - connected_clients: #Number of client connections (excluding connections from slaves)
                alias: "connected_clients"
            - blocked_clients: #Number of clients pending on a blocking call(BLPOP, BRPOP, BRPOPLPUSH)
                alias: "blocked_clients"

        Memory: #Information about the memory consumption
            - used_memory: #Total number of bytes allocated by Redis using its allocator (either standard libc, jemalloc, or an alternative allocator such as tcmalloc
                alias: "used_memory"
            - used_memory_rss: #Number of bytes that Redis allocated as seen by the operating system (a.k.a resident set size). This is the number reported by tools such as top(1) and ps(1)
                alias: "used_memory_rss"
            - used_memory_peak: #Peak memory consumed by Redis (in bytes)
                alias: "used_memory_peak"
            - used_memory_lua: #Number of bytes used by the Lua engine
                alias: "used_memory_lua"
            - mem_fragmentation_ratio: #Ratio between used_memory_rss and used_memory
                alias: "mem_fragmentation_ratio"


        Persistence: #Information related to RDB and AOF
            - rdb_changes_since_last_save: #Number of changes since the last dump
                alias: "rdb_changes_since_last_save"
            - rdb_last_bgsave_time_sec: #Duration of the last RDB save operation in seconds
                alias: "rdb_last_bgsave_time_sec"
            - rdb_current_bgsave_time_sec: #Duration of the on-going RDB save operation if any
                alias: "rdb_current_bgsave_time_sec"
            - aof_last_rewrite_time_sec: #Duration of the last AOF rewrite operation in seconds
                alias: "aof_last_rewrite_time_sec"
            - aof_current_rewrite_time_sec: #Duration of the on-going AOF rewrite operation if any
                alias: "aof_current_rewrite_time_sec"

        Stats: #General statistics
            - total_connections_received:  #Total number of connections accepted by the server
                alias: "total_connections_received"
            - total_commands_processed: #Total number of commands processed by the server
                alias: "total_commands_processed"
            - instantaneous_ops_per_sec: #Number of commands processed per second
                alias: "instantaneous_ops_per_sec"
            - rejected_connections: #Number of connections rejected because of maxclients limit
                alias: "rejected_connections"
            - expired_keys: #Total number of key expiration events
                alias: "expired_keys"
            - evicted_keys: #Number of evicted keys due to maxmemory limit
                alias: "evicted_keys"
            - keyspace_hits: #Number of successful lookup of keys in the main dictionary
                alias: "keyspace_hits"
            - keyspace_misses: #Number of failed lookup of keys in the main dictionary
                alias: "keyspace_misses"
            - pubsub_channels: #Global number of pub/sub channels with client subscriptions
                alias: "pubsub_channels"
            - pubsub_patterns: #Global number of pub/sub pattern with client subscriptions
                alias: "pubsub_patterns"
            - latest_fork_usec: #Duration of the latest fork operation in microseconds
                alias: "latest_fork_usec"

        Replication: #Information related to Master/Slave replication
            - role:
                alias: "role"
                convert:
                    master: "1"
                    slave: "0"
            - connected_slaves: #Number of connected slaves
                alias: "connected_slaves"

        CPU: #Information related to CPU consumption
            - used_cpu_sys: #System CPU consumed by the Redis server
                alias: "used_cpu_sys"
            - used_cpu_user: #User CPU consumed by the Redis server
                alias: "used_cpu_user"
            - used_cpu_sys_children: #System CPU consumed by the background processes
                alias: "used_cpu_sys_children"
            - used_cpu_user_children: #User CPU consumed by the background processes
                alias: "used_cpu_user_children"

derivedMetrics:
    - derivedMetricPath: "{x}|Stats|keyspace_hit_ratio"
      formula: "{x}|Stats|keyspace_hits / ({x}|Stats|keyspace_hits + {x}|Stats|keyspace_misses)"









